Traceback (most recent call last):
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in main
    process.wait()
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/subprocess.py", line 1032, in wait
    self._wait(timeout=sigint_timeout)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/subprocess.py", line 1647, in _wait
    time.sleep(delay)
KeyboardInterrupt
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/relation_test_net.py", line 162, in <module>
  File "tools/relation_test_net.py", line 162, in <module>
        main()main()

  File "tools/relation_test_net.py", line 69, in main
  File "tools/relation_test_net.py", line 69, in main
    torch.cuda.set_device(args.local_rank)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/cuda/__init__.py", line 263, in set_device
    torch.cuda.set_device(args.local_rank)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/cuda/__init__.py", line 263, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
KeyboardInterrupt
    torch._C._cuda_setDevice(device)
  File "/home/scene/.conda/envs/sg_benchmark/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
KeyboardInterrupt
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 476, in <module>
    main()
  File "tools/relation_train_net.py", line 424, in main
    cfg.merge_from_file(args.config_file)
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 476, in <module>
    self.merge_from_other_cfg(cfg)
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    main()
  File "tools/relation_train_net.py", line 424, in main
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    cfg.merge_from_file(args.config_file)
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    self.merge_from_other_cfg(cfg)
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.ROI_RELATION_HEAD.EXPERT_MODE'
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/scene/.local/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.ROI_RELATION_HEAD.EXPERT_MODE'
Traceback (most recent call last):
  File "/home/scene/.conda/envs/came/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/home/scene/.conda/envs/came/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/scene/.conda/envs/came/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scene/.conda/envs/came/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/scene/.conda/envs/came/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scene/.conda/envs/came/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/scene/.conda/envs/came/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    process.wait()
  File "/home/scene/.conda/envs/came/lib/python3.7/subprocess.py", line 1032, in wait
    self._wait(timeout=sigint_timeout)
  File "/home/scene/.conda/envs/came/lib/python3.7/subprocess.py", line 1647, in _wait
    time.sleep(delay)
KeyboardInterrupt
